config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    "tasks",            to: "tasks#index"

  get    "tasks/new",        to: "tasks#new", as: :new_task
  post   "tasks",            to: "tasks#create"

    # NB: The `show` route needs to be *after* `new` route.
  get    "tasks/:id",        to: "tasks#show", as: :task

  get    "tasks/:id/edit",   to: "tasks#edit", as: :task_edit
  patch  "tasks/:id",        to: "tasks#update"

  delete "tasks/:id",        to: "tasks#destroy", as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    # 1 Read
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  # 2 Create
  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to(tasks_path)
  end

  # 3 Update
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path
  end

  # 4 Destroy
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container text-center">

  <h1>Edit your task</h1>

  <%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
   </div>
   <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details %>
   </div>
   <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
   </div>
    <%= f.submit class:'btn btn-primary' %>
  <% end %>

  <%= link_to  "back to tasks", tasks_path, class:'btn btn-primary mt-3'  %>
</div>

app/views/tasks/index.html.erb
<div class="container text-center">

  <h1>All Tasks</h1>

    <% @tasks.each do |task| %>

     <p><% if task.completed %>
      <i class="fas fa-clipboard-check"></i>
      <% else %>
      <i class="fas fa-clipboard"></i>
      <% end %>
      <%= link_to task.title, task_path(task), class:'btn btn-light'%> --- <%= link_to  task_delete_path(task[:id]),
        method: :delete,
        data: { confirm: "Are you sure?" } do %>
        <i class="far fa-trash-alt"></i>
        <% end %>
      </p>
    <% end %>
     <p>
      <%= link_to "Create a new task", new_task_path, class:'btn btn-primary' %></p>

</div>
  <!-- <i class="fas fa-clipboard-check"> -->

app/views/tasks/new.html.erb
<div class="container text-center">

  <h1>Create a new Task</h1>

  <!-- <form action="/tasks" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <label for="task">task: </label>
    <input type="text" name="task[title]" id="title">

    <label for="details">details: </label>
    <input type="text" name="task[details]" id="details">

    <input type="submit">
  </form> -->
  <div class="mx-auto my-5">

    <%= form_for(@task) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class:"from-control text-left" %>
      </div>
      <div class="form-group">
        <%= f.label :details %>
        <%= f.text_field :details, class:"from-control text-left" %>
      </div>
      <%= f.submit class:'btn btn-primary' %>
    <% end %>
  </div>

  <%= link_to "back to tasks", tasks_path, class:'btn btn-danger mb-3'  %>
</div>

app/views/tasks/show.html.erb
<div class="container text-center">

  <h1><%= @task.title %></h1>
  <h3><%= @task.details %></h3>
  <%= link_to "back to tasks", tasks_path,, class:'btn btn-primary'  %>
  <%= link_to "Edit", task_edit_path(@task), class:'btn btn-success'  %>
</div>